module.exports = {
    article: require('./article.jsx'),
    avgGrid: require('./avgGrid.jsx'),
    badge: require('./badge.jsx'),
    button: require('./button.jsx'),
    close: require('./close.jsx'),
    dateTimeInput: require('./dateTimeInput.jsx'),
    dateTimePicker: require('./dateTimePicker.jsx'),
    dropdown: require('./dropdown.jsx'),
    form: require('./form.jsx'),
    goTop: require('./goTop.jsx'),
    header: require('./header.jsx'),
    icon: require('./icon.jsx'),
    input: require('./input.jsx'),
    list: require('./list.jsx'),
    menu: require('./menu.jsx'),
    modal: require('./modal.jsx'),
    modalTrigger: require('./modalTrigger.jsx'),
    nav: require('./nav.jsx'),
    tab: require('./tab.jsx'),
    pagination: require('./pagination.jsx'),
    selected: require('./selected.jsx'),
    table: require('./table.jsx'),
    tabs: require('./tabs.jsx'),
    uiCheck: require('./uiCheck.jsx'),
};
