module.exports = {
    article: require('./article'),
    avgGrid: require('./avgGrid'),
    badge: require('./badge'),
    button: require('./button'),
    close: require('./close'),
    dateTimeInput: require('./dateTimeInput'),
    dateTimePicker: require('./dateTimePicker'),
    dropdown: require('./dropdown'),
    form: require('./form'),
    goTop: require('./goTop'),
    header: require('./header'),
    icon: require('./icon'),
    input: require('./input'),
    list: require('./list'),
    menu: require('./menu'),
    modal: require('./modal'),
    modalTrigger: require('./modalTrigger'),
    nav: require('./nav'),
    pagination: require('./pagination'),
    selected: require('./selected'),
    table: require('./table'),
    tabs: require('./tabs'),
    uiCheck: require('./uiCheck'),
};
